services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MercuryKojo\Bundle\UniversalCommentBundle\Controller\:
    resource: '../../Controller'
    public: true
    tags: ['controller.service_arguments']

  # Twig extensions
  MercuryKojo\Bundle\UniversalCommentBundle\Twig\:
    resource: '../../Twig'
    public: true
    tags: ['twig.extension']


  MercuryKojo\Bundle\UniversalCommentBundle\Installation\Installer:
    public: true

  MercuryKojo\Bundle\UniversalCommentBundle\Templating\Helper\UniversalCommentHelper:
    public: true
    arguments: ['@Symfony\Component\Templating\EngineInterface', '@request_stack']
    tags:
    - { name: templating.helper, alias: universalComment }

